---
rule-providers:
  Direct:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/latifangren/CLASH-CONFIG-by-Latifan/main/rule_provider/direct.yaml"
    path: "./rule_provider/direct.yaml"
    interval: 86400
  Umum:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/latifangren/CLASH-CONFIG-by-Latifan/main/rule_provider/umum.yaml"
    path: "./rule_provider/umum.yaml"
    interval: 86400
  Reject:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/latifangren/CLASH-CONFIG-by-Latifan/main/rule_provider/reject.yaml"
    path: "./rule_provider/reject.yaml"
    interval: 86400
  Streaming:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/latifangren/CLASH-CONFIG-by-Latifan/main/rule_provider/streaming.yaml"
    path: "./rule_provider/streaming.yaml"
    interval: 86400
  Games:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/latifangren/CLASH-CONFIG-by-Latifan/main/rule_provider/games.yaml"
    path: "./rule_provider/games.yaml"
    interval: 86400
  Sosmed:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/latifangren/CLASH-CONFIG-by-Latifan/main/rule_provider/sosmed.yaml"
    path: "./rule_provider/sosmed.yaml"
    interval: 86400
  Ewallet:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/latifangren/CLASH-CONFIG-by-Latifan/main/rule_provider/ewallet.yaml"
    path: "./rule_provider/ewallet.yaml"
    interval: 86400
  China:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China_Classical.yaml"
    path: "./rule_provider/china.yaml"
    interval: 86400
  ChinaDomain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China_Domain.yaml"
    path: "./rule_provider/china_domain.yaml"
    interval: 86400
  AdBlock:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising_Domain.yaml"
    path: "./rule_provider/adblock.yaml"
    interval: 86400
  Malware:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Malware/Malware_Domain.yaml"
    path: "./rule_provider/malware.yaml"
    interval: 86400
      # Provider Cloud Configuration
  # cc=ID            : Hanya mengambil server Indonesia
  # format=raw       : Format output dalam bentuk raw
  # limit=20         : Batasan maksimal 20 akun
  # vpn=trojan       : Hanya mengambil akun trojan
  # port=443         : Menggunakan port 443
  # domain=172.67.5.14 : IP yang digunakan
  # host=bug.com     : SNI/Host ganti dengan bug kalian
proxy-providers:
  "provide-us":
    type: http
    url: "https://nautica.foolvpn.me/api/v1/sub/?cc=US&format=raw&limit=4&vpn=trojan&port=443&domain=172.67.5.14&host=bug.com&update=1"
    interval: 3600
    path: ./provide/us.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 3600

  "provide-sg":
    type: http
    url: "https://nautica.foolvpn.me/api/v1/sub/?cc=SG&format=raw&limit=4&vpn=trojan&port=443&domain=172.67.5.14&host=bug.com&update=1"
    interval: 3600
    path: ./provide/sg.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 3600

  "provide-id":
    type: http
    url: "https://nautica.foolvpn.me/api/v1/sub/?cc=ID&format=raw&limit=4&vpn=trojan&port=443&domain=172.67.5.14&host=bug.com&update=1"
    interval: 3600
    path: ./provide/id.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 3600

  "provide-jp":
    type: http
    url: "https://nautica.foolvpn.me/api/v1/sub/?cc=JP&format=raw&limit=4&vpn=trojan&port=443&domain=172.67.5.14&host=bug.com&update=1"
    interval: 3600
    path: ./provide/jp.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 3600

  # Provider Cloud Configuration
  # cc=ID            : Hanya mengambil server Indonesia
  # format=raw       : Format output dalam bentuk raw
  # limit=20         : Batasan maksimal 20 akun
  # vpn=trojan       : Hanya mengambil akun trojan
  # port=443         : Menggunakan port 443
  # domain=172.67.5.14 : IP yang digunakan
  # host=bug.com     : SNI/Host ganti dengan bug kalian
  "provide-china":
    type: http
    url: "https://nautica.foolvpn.me/api/v1/sub/?cc=CN&format=raw&limit=20&vpn=trojan&port=443&domain=172.67.5.14&host=bug.com&update=1"
    interval: 3600
    path: ./provide/china.yml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 3600

  ID:
    type: file
    path: "./proxy_provider/ID.yaml"
    health-check:
      enable: true
      url: https://cp.cloudflare.com/generate_204
      interval: 30

  SG:
    type: file
    path: "./proxy_provider/SG.yaml"
    health-check:
      enable: true
      url: https://cp.cloudflare.com/generate_204
      interval: 30
proxy-groups:
- name: Ewallet
  type: select
  disable-udp: false
  proxies:
  - Auto
  - Manual
  - ID-LB
  - SG-LB
  - LB ID-SG
- name: Games
  type: select
  disable-udp: false
  proxies:
  - Auto
  - Manual
  - ID-LB
  - SG-LB
  - LB ID-SG
  - DIRECT
- name: Streaming
  type: select
  disable-udp: false
  proxies:
  - Auto
  - Manual
  - ID-LB
  - SG-LB
  - LB ID-SG
- name: Sosmed
  type: select
  disable-udp: false
  proxies:
  - Auto
  - Manual
  - Streaming
  - ID-LB
  - SG-LB
  - LB ID-SG
- name: Manual
  type: select
  disable-udp: false
  use:
  - ID
  - SG
  - provide-us
  - provide-sg
  - provide-id
  - provide-jp
- name: Auto
  type: fallback
  disable-udp: false
  use:
  - ID
  - SG
  url: https://cp.cloudflare.com/generate_204
  interval: 30
- name: Best Ping
  type: url-test
  disable-udp: false
  use:
  - ID
  - SG
  - "provide-us"
  - "provide-sg"
  - "provide-id"
  - "provide-jp"
  url: https://cp.cloudflare.com/generate_204
  interval: 30
  tolerance: 60
- name: ID-LB
  type: load-balance
  strategy: round-robin
  disable-udp: false
  use:
  - ID
  url: https://cp.cloudflare.com/generate_204
  interval: 30
- name: SG-LB
  type: load-balance
  strategy: round-robin
  disable-udp: false
  use:
  - SG
  url: https://cp.cloudflare.com/generate_204
  interval: 30
- name: LB ID-SG
  type: load-balance
  strategy: round-robin
  disable-udp: false
  use:
  - ID
  - SG
  url: https://cp.cloudflare.com/generate_204
  interval: 30
- name: GLOBAL
  type: select
  proxies:
    - Auto
    - Best Ping
    - Manual
    - ID-LB
    - SG-LB
    - LB ID-SG
- name: CHINA
  type: url-test
  disable-udp: false
  use:
    - "provide-china"
dns:
  nameserver:
    - https://dns.google/dns-query
    - https://cloudflare-dns.com/dns-query
    - tls://1.1.1.1:853
    - tls://8.8.8.8:853
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  listen: 0.0.0.0:1053
  fake-ip-filter:
    - "*.lan"
    - "*.local"
    - "dns.msftncsi.com"
    - "www.msftncsi.com"
    - "www.msftconnecttest.com"
    - "stun.*.*"
    - "stun.*.*.*"
    - "+.stun.*.*"
    - "+.stun.*.*.*"
    - "+.stun.*.*.*.*"
    - "lens.l.google.com"
    - "stun.l.google.com"
    - "+.n.n.srv.nintendo.net"
    - "+.srv.nintendo.net"
    - "+.ntp.org.cn"
    - "+.pool.ntp.org"
    - "ntp.ubuntu.com"
    - "time.apple.com"
    - "time.asia.apple.com"
    - "time.euro.apple.com"
    - "time.windows.com"
    - "xbox.*.microsoft.com"
    - "*.*.xboxlive.com"
    - "+.*"
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  fallback:
    - https://cloudflare-dns.com/dns-query
    - 1.0.0.1
    - 8.8.4.4
  fallback-filter:
    geoip: true
    geoip-code: ID
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
      - '+.githubusercontent.com'
      - '+.googlevideo.com'
      - '+.msftconnecttest.com'
      - '+.msftncsi.com'
  respect-rules: true
  proxy-server-nameserver:
    - 9.9.9.9
    - 8.8.8.8
    - 1.1.1.1
  fake-ip-range: 198.18.0.1/16
redir-port: 9797
tproxy-port: 9898
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
log-level: silent
allow-lan: true
unified-delay: true
external-controller: 0.0.0.0:9090 
# secret: "123456"

bind-address: "*"
external-ui: /data/adb/box/clash/dashboard
ipv6: false
rules:
- RULE-SET,China,CHINA
- RULE-SET,ChinaDomain,CHINA
- DST-PORT,7895,REJECT
- DST-PORT,7892,REJECT
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- DST-PORT,7895,REJECT
- DST-PORT,7892,REJECT
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- AND,((NOT,((DST-PORT,80/81/443/8000-8081/21/22/23/81/88/5050/843/182/53))),(NETWORK,UDP)),Games
- AND,((NOT,((DST-PORT,80/81/443/8000-8081/21/22/23/81/88/5050/843/182/53))),(NETWORK,TCP)),Games
- AND,((NETWORK,UDP),(OR,((DST-PORT,443),(GEOSITE,youtube)))),REJECT
- RULE-SET,Sosmed,Sosmed
- RULE-SET,Ewallet,Ewallet
- RULE-SET,Streaming,Streaming
- RULE-SET,Games,Games
- RULE-SET,Umum,GLOBAL
- RULE-SET,Direct,DIRECT
- RULE-SET,Reject,REJECT
- RULE-SET,AdBlock,REJECT
- RULE-SET,Malware,REJECT
- DOMAIN-SUFFIX,ads.google.com,REJECT
- DOMAIN-SUFFIX,ads-twitter.com,REJECT
- DOMAIN-SUFFIX,ads.facebook.com,REJECT
- DOMAIN-KEYWORD,adservice,REJECT
- DOMAIN-KEYWORD,analytics,REJECT
- DOMAIN-KEYWORD,advertisement,REJECT
- DOMAIN-SUFFIX,doubleclick.net,REJECT
- DOMAIN-SUFFIX,googleadservices.com,REJECT
- DOMAIN-SUFFIX,google-analytics.com,REJECT
- DOMAIN-SUFFIX,adform.net,REJECT
- DOMAIN-SUFFIX,admob.com,REJECT
- DOMAIN-SUFFIX,advertiserservers.com,REJECT
- MATCH,GLOBAL
experimental:
  ignore-resolve-fail: true
  sniff-tls-sni: true
  tracing: true
hosts:
  localhost: 127.0.0.1
profile:
  store-selected: true
  store-fake-ip: true
sniffer:
  enable: true
  parse-pure-ip: true
tcp-concurrent: true
geodata-loader: memconservative
keep-alive-interval: 15
global-client-fingerprint: chrome
keep-alive-idle: 120
authentication:
- Clash:ACm8NSSW

# Konfigurasi TUN
tun:
  enable: true
  stack: system
  dns-hijack:
    - any:53
  auto-route: true
  auto-detect-interface: true
  device: meta
  mtu: 9000
  
  include_android_user:
    - 0
    - 10
  
  include_package:
    # Game Popular
    - com.mobile.legends
    - com.tencent.ig
    - com.pubg.imobile
    - com.garena.game.codm
    - com.activision.callofduty.shooter
    - com.dts.freefireth
    - com.dts.freefiremax
    - com.supercell.clashofclans
    - com.supercell.brawlstars
    - com.miHoYo.GenshinImpact
    - com.riotgames.league.wildrift
    - com.riotgames.legendsofruneterra
    - com.garena.game.kgid
    - com.garena.game.kgth
    - com.epicgames.fortnite
    - com.ea.gp.fifamobile
    - com.gameloft.android.ANMP.GloftA9HM
    # Aplikasi Umum
    - com.android.chrome
    - com.android.vending
    - com.google.android.gms
    - com.google.android.gsf
    - com.android.providers.downloads
    - com.google.android.apps.maps
    - com.whatsapp
    - com.facebook.katana
    - com.instagram.android
    - com.twitter.android
    - com.google.android.youtube
